@startuml
'https://plantuml.com/class-diagram

package com.baomidou.mybatisplus.core.injector {
  abstract class AbstractMethod
}

package com.baomidou.mybatisplus.core.injector.methods {
  class Delete
  class SelectById
  class SelectOne
}

package com.baomidou.mybatisplus.core.enums {
  enum SqlMethod
}

AbstractMethod <|-- Delete
AbstractMethod <|-- SelectById
AbstractMethod <|-- SelectOne

@enduml