@startmindmap
'https://plantuml.com/mindmap-diagram

+ igauto/rms（车联网运营管理平台）
++ 车辆中心
+++ 车辆档案
++++ 新增/导入
+++ 车辆全生命周期
++++ 数据采集
++++ 数据清洗
++++ 数据统计
++++ 数据分析
++ 设备中心
+++ Tbox
+++ 行车记录仪
-- 业务中心
-- 风控中心
--- 实时报警
--- 历史报警
--- 事件提醒
++ 数据中心
+++ 车辆统计
+++ 设备统计
+++ 里程统计
+++ 能耗统计
+++ 报警统计
+++ 在线时长
+++ 车速统计
-- 管理中心
-- 系统设置
--- POI
---- 充电
---- 停车场
---- 洗车
---- 救援
---- 服务站点
@endmindmap
