@startuml
'https://plantuml.com/class-diagram

class MappedStatement {
	+ BoundSql getBoundSql
}
class BoundSql
interface SqlSource {
	+ BoundSql getBoundSql
}
class DynamicSqlSource
class ProviderSqlSource
class RawSqlSource
class StaticSqlSource
SqlSource <|-- DynamicSqlSource
SqlSource <|-- ProviderSqlSource
SqlSource <|-- RawSqlSource
SqlSource <|-- StaticSqlSource
SqlSource ..> BoundSql
MappedStatement --> SqlSource

@enduml